name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: python setup.py install
  
  lint:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with black
      run: |
        pip install black
        black --check -l 120 .
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Tests
      run: |
        pip install pytest
        pytest tests
